### ISSUE TITLE
If the cloudant->dash data movement task fails, the pipe will still report success

### ISSUE THREAD

**Issue by johnnason** [ibm-watson-data-lab/pipes#30]
I had about 6 tables that fundamentally failed to move from Cloudant to dashDB via dataworks. The dataworks jobs were failing without creating any records. The overall status of the pipe comes back as success. Didn't know there was a real problem until we started looking at the data in dash and were wondering where a few key tables were.

**Comment by lornajane** [comment]
Thanks for the bug report!  In case it wasn't already obvious, this repo is no longer supported.  I'm closing this issue to make clear that it won't be attended to.
